### ISSUE TITLE
Make Triumph gui multithread 

### ISSUE THREAD

**Issue by ImFound** [TriumphTeam/triumph-gui#40]
Hey! You could make Triumph gui multithread? Because if not different querys to mysql are bugged.

**Comment by ImFound** [comment]
(like SELECT * FROM (table) WHERE player_uuid=?

**Comment by Kqliber** [comment]
The majority of the Bukkit API is not thread safe, and I believe this includes GUIs, and will cause errors when attempting to open a GUI on another thread. so this is impossible.
With that being said, if you need to query a database in your GUI, you should be caching the results beforehand and accessing them through the cache, instead of querying from directly inside the GUI.
